[project]
name = "doam"
version = "0.1.0"
description = "doam is a Pycord-based Discord bot that runs Major League Redditball's competitive home run derby number guessing minigame."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "py-cord>=2.7.1",
    "redis>=7.4.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.9",
    "ty>=0.0.27",
]
